TaskCaller/Controllers/ExecuteLogController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using TaskCaller.Services;
using TaskCaller.UI;

namespace SchedulerLite.Manager.Controllers
{
    [Authorize]
    public class ExecuteLogController : Controller
    {
        
        ExecuteLogService _executeLogService;
        public ExecuteLogController(ExecuteLogService executeLogService)
        {
            _executeLogService = executeLogService;
        }

        // GET: ExecuteLog
        public ActionResult List(long taskId = 0, int taskType = 0, int status = 0, int page = 1)
        {
            var pageSize = 10;
            var plist = _executeLogService.SearchList(taskId, taskType, status, page, pageSize);
            ViewBag.plist = plist.ToStaticPagedList();
            return View();
        }

    }
}

TaskCaller/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 任务调度系统</title>
    <link href="~/lib/layui/css/layui.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/PagedList.css" rel="stylesheet" />
</head>
<body class="layui-layout-body">
    <div class="layui-layout layui-layout-admin">
        <div class="layui-header">
            <div class="layui-logo">任务调度系统</div>
            <!-- 头部区域（可配合layui已有的水平导航） -->

            <ul class="layui-nav layui-layout-right">
                <li class="layui-nav-item"><a href="@Url.Action("logout","account")">退出</a></li>
            </ul>


        </div>
        <div class="layui-side layui-bg-black">
            <div class="layui-side-scroll">
                <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
                <ul class="layui-nav layui-nav-tree">
                    <li class="layui-nav-item layui-nav-itemed">
                        <a class="" href="javascript:;">任务</a>
                        <dl class="layui-nav-child">
                            <dd class="@("timedTask".Equals(ViewBag.nav) ? "layui-this" : "")"><a href="@Url.Action("list", "timedTask")">定时任务</a></dd>
                            <dd class="@("delayTask".Equals(ViewBag.nav) ? "layui-this" : "")"><a href="@Url.Action("list", "delayTask")">延迟任务</a></dd>
                            <dd class="@("log".Equals(ViewBag.nav) ? "layui-this" : "")"><a href="@Url.Action("list", "ExecuteLog")">任务日志</a></dd>
                        </dl>
                    </li>
                </ul>
            </div>
        </div>

        <div class="layui-body">
            <!-- 内容主体区域 -->
            <div style="padding: 15px;">
                @RenderBody()
            </div>
        </div>

        <div class="layui-footer">
            <!-- 底部固定区域 -->
            © 2019
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/layui/layui.all.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>